-- Fix duplicate indexes reported by Supabase (run in Supabase Dashboard → SQL Editor)
-- Run once. Idempotent where possible.
-- If you see more "identical indexes" warnings for other tables, add similar
-- DROP INDEX IF EXISTS for the duplicate (keep the one from migrations / named index).

-- ============================================
-- 1. AuditLogs: two identical indexes on (createdAt)
--    Keep: audit_logs_created_at_idx (from migration)
--    Drop: audit_logs_created_at (auto-generated by Sequelize model)
-- ============================================
DROP INDEX IF EXISTS public.audit_logs_created_at;

-- ============================================
-- 2. Integrations: two identical unique indexes on (userId, provider)
--    Keep: integrations_user_provider_unique (from migration)
--    Drop: integrations_user_id_provider (auto-generated)
-- ============================================
DROP INDEX IF EXISTS public.integrations_user_id_provider;

-- ============================================
-- 3. Users: many duplicate unique indexes on (username)
--    Drop all "Users_username_key*" and leave a single unique index.
-- ============================================
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT indexname
    FROM pg_indexes
    WHERE schemaname = 'public'
      AND tablename = 'Users'
      AND indexname LIKE 'Users_username_key%'
  LOOP
    EXECUTE format('DROP INDEX IF EXISTS public.%I', r.indexname);
  END LOOP;

  -- Recreate a single unique index on username
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public' AND tablename = 'Users'
      AND indexname = 'users_username_unique'
  ) THEN
    CREATE UNIQUE INDEX users_username_unique ON public."Users" (username);
  END IF;
END $$;
